# Generated by Django 2.2.5 on 2019-09-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_pcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('district_name_eng', models.CharField(max_length=30)),
                ('district_name_mmr', models.CharField(max_length=30)),
                ('myainfo_d_id', models.CharField(blank=True, max_length=13, null=True)),
                ('source', models.CharField(max_length=3)),
                ('start_date', models.DateField()),
                ('modified_end_date', models.DateField(blank=True, null=True)),
                ('notification', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_modified', models.CharField(blank=True, max_length=100, null=True)),
                ('district_status', models.CharField(default='active', max_length=8)),
                ('change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateRegion',
            fields=[
                ('sr_pcode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('sr_name_eng', models.CharField(max_length=30)),
                ('sr_name_mmr', models.CharField(max_length=30)),
                ('myainfo_sd_id', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=3)),
                ('start_date', models.DateField()),
                ('modified_end_date', models.DateField(blank=True, null=True)),
                ('notification', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_modified', models.CharField(blank=True, max_length=100, null=True)),
                ('sr_status', models.CharField(default='active', max_length=8)),
                ('change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('tsp_pcode', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('township_name_eng', models.CharField(max_length=30)),
                ('township_name_mmr', models.CharField(max_length=30)),
                ('myainfo_ts_id', models.CharField(max_length=12)),
                ('source', models.CharField(max_length=3)),
                ('start_date', models.DateField()),
                ('modified_end_date', models.DateField(blank=True, null=True)),
                ('notification', models.CharField(blank=True, max_length=50, null=True)),
                ('notification_modified', models.CharField(blank=True, max_length=100, null=True)),
                ('township_status', models.CharField(default='active', max_length=8)),
                ('change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('district_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townships', to='facility.District')),
                ('sr_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townships', to='facility.StateRegion')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name_eng', models.CharField(max_length=50)),
                ('facility_name_mmr', models.CharField(max_length=50)),
                ('district_pcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='facility.District')),
                ('sr_pcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='facility.StateRegion')),
                ('tsp_pcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='facility.Township')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='sr_pcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='facility.StateRegion'),
        ),
    ]
