# Generated by Django 2.2.5 on 2019-09-21 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('registration_group', models.PositiveIntegerField()),
                ('specimen_collected_date', models.DateField()),
                ('x_pert_result', models.CharField(max_length=5)),
                ('x_pert_result_date', models.DateField()),
                ('culture_result', models.CharField(max_length=10)),
                ('dst_result', models.CharField(max_length=10)),
                ('died_before_treatment', models.BooleanField(default=False)),
                ('died_before_treatment_date', models.DateField()),
                ('sld_treatment_at_private_date', models.DateField()),
                ('refused_date', models.DateField()),
                ('lfu_date', models.DateField()),
                ('mdr_treatment_start_date', models.DateField()),
                ('mdr_treatment_registration_no', models.CharField(max_length=10)),
                ('remark', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to=settings.AUTH_USER_MODEL)),
                ('name_of_treatment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='facility.Facility')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify', to='facility.Township')),
            ],
        ),
    ]
