# Generated by Django 2.2.5 on 2019-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='culture_result',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='notify',
            name='died_before_treatment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='died_before_treatment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='dst_result',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='notify',
            name='lfu_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='mdr_treatment_registration_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='mdr_treatment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='refused_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=200),
        ),
        migrations.AlterField(
            model_name='notify',
            name='sld_treatment_at_private_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='x_pert_result',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('RR', 'RR'), ('TI', 'TI')], max_length=5),
        ),
    ]
