# Generated by Django 2.2.5 on 2019-09-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntp', '0002_auto_20190921_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='x_pert_result',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('RR', 'RR'), ('TI', 'TI')], max_length=5, null=True),
        ),
    ]
