# Generated by Django 2.2.5 on 2019-09-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntp', '0003_auto_20190921_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='specimen_collected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='x_pert_result_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
